{{- if and .Values.google (eq .Values.mode "recovery") (eq .Values.recovery.method "object_store") (eq .Values.recovery.provider "google") .Values.recovery.google.applicationCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster.fullname" . }}-backup-google-recovery-creds
data:
  APPLICATION_CREDENTIALS: {{ .Values.recovery.google.applicationCredentials | b64enc | quote }}
{{- end }}